name = "api-playground"
main = "worker.js"
compatibility_date = "2024-09-23"

# Configuración de la base de datos D1
[[d1_databases]]
binding = "DB"
database_name = "api-playground"
database_id = "566be1f8-02cb-4249-a4b7-a6e5004c9e38"

# Variables de entorno para production
[env.production.vars]
NODE_ENV = "production"
API_VERSION = "1.0.0"
MAX_POSTS_PER_PAGE = "50"
MAX_COMMENTS_PER_PAGE = "100"

# Variables de entorno para staging
[env.staging.vars]
NODE_ENV = "staging"
API_VERSION = "1.0.0"
MAX_POSTS_PER_PAGE = "25"
MAX_COMMENTS_PER_PAGE = "50" 